name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4

    - name: Install dependencies
      run: bundle install

    - name: Jekyll build
      run: bundle exec jekyll build
